# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  link_to_zsh:
    cmds:
      - sudo ln -sf /bin/zsh /bin/sh
  enable_aslr:
    desc: "Enable Address Space Layout Randomization (ASLR)"
    cmds:
      - "sudo sysctl -w kernel.randomize_va_space=2"
      - "cat /proc/sys/kernel/randomize_va_space"

  disable_aslr:
    desc: "Disable Address Space Layout Randomization (ASLR)"
    cmds:
      - "sudo sysctl -w kernel.randomize_va_space=0"
      - "cat /proc/sys/kernel/randomize_va_space"
  install-pre-requisites:
    cmds:
      - sudo apt install -y nala 
      - sudo nala install -y python3-dev git libssl-dev libffi-dev build-essential
    silent: false
  install-pwntools:
    cmds:
      - python3 -m pip install --upgrade --break-system-packages pip
      - python3 -m pip install --upgrade --break-system-packages pwntools
    silent: false
  install-pwndbg:
    cmds:
      - git clone https://github.com/pwndbg/pwndbg
      - cd pwndbg && ./setup.sh
    silent: false

  install-tools:
    cmds:
      - task: install-pre-requisites
      - task: install-pwntools
      - task: install-pwndbg
    silent: false