version: '3'

tasks:
  setup:
    cmds:
      - curl -o Crypto_RSA.pdf https://seedsecuritylabs.org/Labs_20.04/Files/Crypto_RSA/Crypto_RSA.pdf
      - curl -o Labsetup.zip https://seedsecuritylabs.org/Labs_20.04/Files/Crypto_RSA/Labsetup.zip
      - unzip Labsetup.zip
      - rm Labsetup.zip
    silent: false
  run:
    cmds:
      - ./taskfive
    silent: false
  build:
    cmds:
      - gcc taskone.c -o taskone -lcrypto
      - gcc tasktwo.c -o tasktwo -lcrypto
      - gcc taskthree.c -o taskthree -lcrypto
      - gcc taskfour.c -o taskfour -lcrypto
      - gcc taskfive.c -o taskfive -lcrypto
    silent: false
  clean:
    cmds:
      - rm -f taskone *.o
      - rm -f tasktwo *.o
      - rm -f taskthree *.o
      - rm -f taskfour*.o
      - rm -f taskfive*.o
    silent: false